#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M
#Gradle
org.gradle.jvmargs=-Xmx8192M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.java.home=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true