package com.pyllar.consumer.config

/**
 * iOS base URL configuration.
 * The value of [IOS_BASE_URL] is generated by the Gradle task `generateIosBuildConfig`
 * based on the `-Ppyllar.flavor=debug|release` property passed at build time.
 *
 * debug   → http://10.222.186.212:8080  (local dev server)
 * release → https://api.pyllar.in       (production)
 */
actual fun getApiBaseUrl(): String = IOS_BASE_URL
